package net.jaimetorres.pila.approval.core.misc;

public enum TipoArchivoSalida {

	ACTIVOS_ARCHIVO_A,
	ACTIVOS_PENSION,
	ACTIVOS_SALUD,
	ACTIVOS_RIESGOS,
	ACTIVOS_CAJAS,
	ACTIVOS_SENA,
	ACTIVOS_ICBF,
	ACTIVOS_ESAP,
	ACTIVOS_MINEDU,
	
	PENSIONADOS_ARCHIVO_A,
	PENSIONADOS_PENSION,
	PENSIONADOS_FONDO_SOLIDARIDAD_PENSIONAL,
	PENSIONADOS_SALUD,
	PENSIONADOS_CAJAS,
	
	MINPS,
	ADRES
}
